name: Deploy my Calc
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: For set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Instull Pip
        run: pip install --upgrade pip
      - name: Install pytest
        run: pip install pytest
      - name: Install lint with Ruff
        run: pip install ruff
      - name: Test application
        run: pytest
